image: registry.nocsi.org/archlinux-dind
stages:
  - build
  - test
  - release

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY:latest

before_script:
  - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
  - make check.env

build:
  stage: build
  script:
    - make build

test:
  stage: test
  script:
    - make test

release-image:
  stage: release
  script:
    - make release
  only:
    - master
